UnloadMenu();
adsm("File", "fhcharc.asp", "", null);
admi("Announcements", "fhan.asp", "", 1);
admi("Calendar", "fhcal.asp", "", 1);
admi("Links", "fhurl.asp", "", 1);
admi("", "", "", 1, "hr.gif");
adsm("Buy Extras", "fhcharx.asp", "", 1);
admi("Changed Appearance", "fhcharxr.asp", "", 6);
admi("Custom Picture", "fhcustomp.asp", "", 6);
admi("Amazing Items", "fhcharxi.asp", "", 6);
admi("Upgraded Item", "fhcharxz.asp", "", 6);
admi("Custom Item Picture", "fhitemimage.asp", "", 6);
admi("Enhancement", "fhcharxc.asp", "", 6);
admi("HC Marketplace", "fhmarkethc.asp", "", 1);
admi("Claim Account Item", "fhaccountitem.asp", "", 1);
admi("", "", "", 1, "hr.gif");
admi("Your Trading Cards", "fhtradingcards.asp", "", 1);
admi("Trophies Earned", "fhtrophies.asp", "", 1);
admi("", "", "", 1, "hr.gif");
admi("Options", "fhoption.asp?G=0", "", 1);
admi("Chat Options", "fhoption.asp?Group=Chat", "", 1);
admi("Channels", "fhchatl.asp", "", 1);
admi("", "", "", 1, "hr.gif");
admi("Change Character", "fhcharc.asp", "", 1);
admi("Logout", "fhlogout.asp", "", 1);
adsm("World", "fh.asp", "", null);
admi("World", "worldmap.asp", "", 25);
adsm("Maps", "map.asp", "", 25);
admi("NPC Locations", "mapnpc.asp", "_blank", 27);
admi("", "", "", 27, "hr.gif");
admi("Treasure", "map2.asp", "", 27);
admi("", "", "", 27, "hr.gif");
admi("Keeps", "mapkeep.asp", "", 27, " ");
admi("Artifacts", "artifacts.asp", "", 27, " ");
admi("Territory", "mappirate.asp", "", 27, " ");
adsm("Reveal", "fhreveal.asp", "", 25);
admi("Players", "fhreveal.asp", "", 35);
admi("Property", "fhrevealb.asp", "", 35);
admi("", "", "", 25, "hr.gif");
admi("Travel", "fhfav.asp?Test=A", "", 25);
admi("Mark", "fh.asp?Mark=1", "", 25);
admi("", "", "", 25, "hr.gif");
admi("Make Portal", "fhmp.asp", "", 25);
admi("Open Portal", "fhpor.asp", "", 25);
admi("", "", "", 25, "hr.gif");
admi("Landmarks", "fhland.asp", "", 25);
admi("Challenges", "fhchallenges.asp", "", 25);
admi("Dungeons", "fhlandd.asp", "", 25);
admi("", "", "", 25, "hr.gif");
admi("Rest", "fhrest.asp?Test=A", "", 25);
adsm("Inventory", "fhInv.asp?InventoryItemID=1&ItemTypeID=1", "", null);
admi("Crafting Supplies", "fhinv.asp?F=-1", "", 50);
adsm("Main Tradeskills", "fhcraft.asp", "", 50);
admi("Alchemy", "fhmake2.asp?SkillID=26", "", 52);
admi("Blacksmithing", "fhmake2.asp?SkillID=25", "", 52);
admi("Carpentry", "fhmake2.asp?SkillID=23", "", 52);
admi("Construction", "fhmake2.asp?SkillID=32", "", 52);
admi("Cooking", "fhmake2.asp?SkillID=59", "", 52);
admi("Dungeon Mastery", "fhmake2.asp?SkillID=27", "", 52);
admi("Floristry", "fhmake2.asp?SkillID=189", "", 52);
admi("Furnishing", "fhmake2.asp?SkillID=140", "", 52);
admi("Leatherworking", "fhmake2.asp?SkillID=17", "", 52);
admi("Stonemasonry", "fhmake2.asp?SkillID=63", "", 52);
admi("Tailoring", "fhmake2.asp?SkillID=58", "", 52);
admi("Tinkering", "fhmake2.asp?SkillID=28", "", 52);
adsm("Class Tradeskills", "fhcraft.asp", "", 50);
admi("Animation", "fhmake2.asp?SkillID=180", "", 65);
admi("Artisan", "fhmake2.asp?SkillID=109", "", 65);
admi("Bewitching", "fhmake2.asp?SkillID=196", "", 65);
admi("Charms", "fhmake2.asp?SkillID=195", "", 65);
admi("Lordship", "fhmake2.asp?SkillID=202", "", 65);
admi("Parlor Tricks", "fhmake2.asp?SkillID=200", "", 65);
admi("Patchcrafting", "fhmake2.asp?SkillID=83", "", 65);
admi("Seamanship", "fhmake2.asp?SkillID=64", "", 65);
admi("Surgery", "fhmake2.asp?SkillID=107", "", 65);
admi("", "", "", 65, "hr.gif");
admi("Bejeweling", "fhbejewel.asp", "", 65);
admi("Grenades", "fhgrenade.asp", "", 65);
admi("Poisoning", "fhpoison.asp", "", 65);
admi("Subterfuge", "fhsubterfuge.asp", "", 65);
admi("Trap", "fhtrap.asp", "", 65);
admi("", "", "", 65, "hr.gif");
admi("Augmenting", "fhmake2.asp?SkillID=209", "", 65);
admi("Blood over Beauty", "fhmake2.asp?SkillID=212", "", 65);
admi("Bolts over Brains", "fhmake2.asp?SkillID=211", "", 65);
adsm("Other Tradeskills", "fhcraft.asp", "", 50);
admi("Inscription", "fhinscribe.asp", "", 85);
adsm("Containers", "fhinv.asp?InventoryItemID=1&ItemTypeID=1", "", 50);
admi("All", "fhinv.asp?InventoryItemID=1&ItemTypeID=1", "", 87);
admi("Backpack", "fhinv.asp?InventoryItemID=1&ItemTypeID=6", "", 87);
admi("Sell Bag", "fhinv.asp?InventoryItemID=1&ItemTypeID=67", "", 87);
admi("Equipped", "fhinv.asp?InventoryItemID=1&ItemTypeID=-1", "", 87);
admi("Trade Bag", "fhtb.asp", "", 87);
admi("Bags", "fhbags.asp", "", 87);
admi("", "", "", 87, "hr.gif");
admi("Maps", "fhinvm.asp", "", 87);
admi("Books", "fhbook.asp", "", 87);
admi("Keys", "fhkey.asp", "", 87);
admi("Equipment", "fhequip.asp", "", 50);
adsm("Expansion Items", "fhinv.asp?F=23", "", 50);
admi("Jurassic Wars", "fhinv.asp?F=23", "", 99);
admi("Uncharted Waters", "fhinv.asp?F=24", "", 99);
admi("Dragons of the East", "fhinv.asp?F=25", "", 99);
admi("Afterlife", "fhinv.asp?F=26", "", 99);
admi("Dark Depths", "fhinv.asp?F=27", "", 99);
adsm("Auctions", "fhauc.asp", "", 50);
admi("All Auctions", "fhauc.asp", "", 105);
admi("Browse", "fhauc2.asp", "", 105);
admi("Comments", "fhauco.asp", "", 105);
admi("", "", "", 105, "hr.gif");
admi("Your Bids", "fhaucb.asp", "", 105);
admi("", "", "", 105, "hr.gif");
admi("Add Auction", "fhauca.asp", "", 105);
admi("Edit Auction", "fhauce.asp", "", 105);
admi("Manage", "fhaucm.asp", "", 105);
admi("", "", "", 105, "hr.gif");
admi("Completed", "fhaucmc.asp", "", 105);
adsm("Actions", "fhunlock.asp", "", 50);
admi("Price", "fhvalue.asp?InventoryItemID=1&ItemTypeID=1", "", 117);
admi("Flags", "fhIFlag.asp?InventoryItemID=1&ItemTypeID=1", "", 117);
admi("Consume", "fheat.asp?InventoryItemID=1", "", 117);
admi("Ready Items", "fhiready.asp", "", 117);
admi("Transmogrify", "fhtransmogrify.asp", "", 117);
admi("", "", "", 117, "hr.gif");
admi("Split", "fhsplit.asp", "", 117);
admi("Stack", "fhstack.asp", "", 117);
admi("Drop", "fhIDrop.asp?InventoryItemID=1&ItemTypeID=1", "", 117);
admi("Disguise", "fhdeception.asp?InventoryItemID=1&ItemTypeID=1", "", 117);
admi("Dismantle", "fhdis.asp?InventoryItemID=1&ItemTypeID=1", "", 117);
admi("", "", "", 117, "hr.gif");
admi("Unlock", "fhunlock.asp", "", 117);
admi("Uncover", "fharch.asp", "", 117);
admi("", "", "", 50, "hr.gif");
admi("Spells", "fhispells.asp", "", 50);
admi("Bonuses", "fhextrai.asp", "", 50);
admi("Bejeweling", "fhinvbejewel.asp", "", 50);
admi("Bewitching", "fhbewitch.asp", "", 50);
admi("Patches", "fhinvpatch.asp", "", 50);
admi("Puzzle", "fhipuzzle.asp", "", 50);
admi("Sets", "fhsspells.asp", "", 50);
admi("", "", "", 50, "hr.gif");
admi("Queue", "fhqueue.asp?Type=AA", "", 50);
adsm("Character", "fhstat.asp", "", null);
admi("Info", "fhstat.asp", "", 142);
admi("Skills", "fhskill.asp?B=&T=AA", "", 142);
adsm("Jobs", "fhwant.asp", "", 142);
admi("All Jobs", "fhwant.asp", "", 145);
admi("Browse", "fhwant2.asp", "", 145);
admi("", "", "", 145, "hr.gif");
admi("Add Job", "fhwanta.asp", "", 145);
admi("Edit Job", "fhwante.asp", "", 145);
admi("Storage", "fhstor.asp", "", 142);
admi("Mount Bonuses", "fhmount.asp", "", 142);
admi("Duels", "fhduelstatus.asp", "", 142);
admi("Trade", "fhtrade.asp", "", 142);
adsm("Statistics", "fhsales.asp", "", 142);
admi("Crimes", "fhcrimes.asp", "", 155);
admi("Dungeons", "fhdungeons.asp", "", 155);
admi("Kills", "fhkills.asp", "", 155);
admi("Sales", "fhsales.asp", "", 155);
admi("Tournaments", "fht2.asp", "", 155);
admi("", "", "", 142, "hr.gif");
admi("Fellowships", "fhgroups.asp", "", 142);
admi("", "", "", 142, "hr.gif");
admi("Quests", "fhquest.asp?Type=AA", "", 142);
admi("", "", "", 142, "hr.gif");
admi("Friends", "fhfriend.asp?Type=AA", "", 142);
admi("Messages", "fhmess.asp?Type=AA", "", 142);
admi("", "", "", 142, "hr.gif");
admi("Shortcuts", "fhmacro.asp?G=0", "", 142);
admi("Responses", "fhresp.asp", "", 142);
admi("", "", "", 142, "hr.gif");
admi("Appearance Profile", "fhcharxcp.asp", "", 142);
adsm("Abilities", "fhstyles.asp", "", null);
admi("Styles", "fhstyles.asp", "", 173);
admi("Ready Styles", "fhstylese.asp", "", 173);
admi("", "", "", 173, "hr.gif");
admi("Spellbook", "fhspells.asp", "", 173);
admi("Ready Spell", "fhspellse.asp", "", 173);
admi("Active", "fhaspells.asp", "", 173);
admi("", "", "", 173, "hr.gif");
admi("Allegiance", "fhals.asp", "", 173);
adsm("Guilds", "fhguilds.asp", "", null);
admi("View", "fhguilds.asp", "", 182);
admi("", "", "", 182, "hr.gif");
admi("Manage / Create", "fhgum.asp", "", 182);
admi("", "", "", 182, "hr.gif");
admi("Roster", "fhgur.asp", "", 182);
admi("Messages", "fhgume.asp", "", 182);
admi("Property", "fhguildsp.asp", "", 182);
adsm("Minions", "fhminions.asp", "", null);
adsm("Manage", "fhminions.asp", "", 190);
admi("Tamed", "fhminions.asp?H=1", "", 191);
admi("Summons", "fhminions.asp?H=2", "", 191);
admi("Vendors", "fhminions.asp?H=3", "", 191);
admi("NPCs", "fhmnpc.asp", "", 191);
admi("", "", "", 191, "hr.gif");
admi("Inventory", "fhmini.asp", "", 191);
admi("Possess", "fhmip.asp", "", 190);
admi("Shopkeep Trade", "fhtpop.asp", "", 190);
admi("Dismiss", "fhminionsd.asp", "", 190);
admi("Mounts", "fhmim.asp", "", 190);
admi("", "", "", 190, "hr.gif");
adsm("Breeding", "fhbreed.asp", "", 190);
admi("Beast Breeding", "fhbreed.asp", "", 203);
admi("Insect Breeding", "fhbreedi.asp", "", 203);
admi("Plant Breeding", "fhbreedp.asp", "", 203);
admi("", "", "", 203, "hr.gif");
admi("Breeding Queue", "fhmq.asp", "", 203);
admi("Price Pets", "fhmvalue.asp", "", 190);
adsm("Property", "fhBM.asp", "", null);
adsm("Manage", "fhbm.asp", "", 210);
admi("All", "fhbm.asp", "", 211);
admi("Owned", "fhbm.asp?Filter=2", "", 211);
admi("Managed", "fhbm.asp?Filter=3", "", 211);
admi("Dungeons", "fhbm.asp?Filter=1", "", 210);
admi("Lordship", "fhlordship.asp", "", 210);
adsm("Vessels", "fhvm.asp", "", 210);
admi("Cargo", "fhcargo.asp", "", 217);
admi("", "", "", 210, "hr.gif");
admi("Price Property", "fhpvalue.asp", "", 210);
admi("Trade", "fhBgt.asp", "", 210);
admi("", "", "", 210, "hr.gif");
admi("Build Deed", "fhmake2.asp?SkillID=32", "", 210);
admi("Build Dungeon", "fhmake2.asp?SkillID=27", "", 210);
adsm("Land", "fhtowns.asp", "", null);
admi("Buy Land", "fhtowns.asp", "", 225);
admi("Manage Land", "fhtm.asp", "", 225);
admi("", "", "", 225, "hr.gif");
admi("Info", "fhti.asp", "", 225);
adsm("Library", "fhlibraryr.asp", "", null);
adsm("Rankings", "rankings.asp", "_blank", 230);
admi("Wanted Criminals", "fhcriminals.asp", "", 231);
admi("Player vs Player", "pvpstandings.asp", "_blank", 231);
admi("", "", "", 230, "hr.gif");
adsm("Races", "fhlibraryr.asp", "", 230);
admi("Races", "fhlibraryr.asp", "", 235);
admi("Race Evolution", "fhlibraryre.asp", "", 235);
admi("Tameable Races", "fhlibraryrt.asp", "", 235);
admi("", "", "", 235, "hr.gif");
admi("Dungeon Spawns", "fhlibraryrd.asp", "", 235);
admi("Mounts", "fhlibraryrm.asp", "", 235);
adsm("Professions", "fhlibraryp.asp", "", 230);
admi("Professions", "fhlibraryp.asp", "", 242);
admi("Profession Evolution", "fhlibrarype.asp", "", 242);
adsm("Uncharted Waters", "fhlibraryv.asp", "", 230);
admi("Vessels", "fhlibraryv.asp", "", 245);
admi("Vessel Items", "fhlibraryvi.asp", "", 245);
admi("", "", "", 245, "hr.gif");
admi("Expansion Items", "fhlibraryiex.asp?E=2", "", 245);
admi("Bejeweling", "fhlibrarybj.asp", "", 245);
adsm("Jurassic Wars", "", "", 230);
admi("Expansion Items", "fhlibraryiex.asp?E=1", "", 251);
adsm("Dragons of the East", "", "", 230);
admi("Dragon Factions", "fhlibrarydragp.asp", "", 253);
admi("Expansion Items", "fhlibraryiex.asp?E=3", "", 253);
adsm("The Afterlife", "", "", 230);
admi("Quests", "fhlibraryqt.asp?SN=&CharsAt=19&P=1", "", 256);
admi("Expansion Items", "fhlibraryiex.asp?E=4", "", 256);
admi("Bewitching", "fhlibrarypl2.asp?Type=BEWITCHING", "", 256);
admi("Charms", "fhlibrarypl2.asp?Type=CHARMS AND HEXES", "", 256);
admi("Hexes", "fhlibrarysp2.asp?CharsAt=195&SN=CHARMS AND HEXES", "", 256);
adsm("Dark Depths", "", "", 230);
admi("Expansion Items", "fhlibraryiex.asp?E=5", "", 262);
admi("", "", "", 230, "hr.gif");
adsm("Items", "fhlibraryi.asp", "", 230);
admi("Sets", "fhlibraryset.asp", "", 265);
admi("", "", "", 265, "hr.gif");
admi("Plans", "fhlibrarypl.asp", "", 265);
admi("Items", "fhlibraryi.asp", "", 265);
admi("Armor", "fhlibrarya.asp", "", 265);
admi("Tools", "fhlibraryit.asp", "", 265);
admi("Weapons", "fhlibraryw.asp", "", 265);
admi("Siege Weapons", "fhlibrarysw.asp", "", 265);
admi("Steal Loot", "fhlibraryisl.asp", "", 265);
admi("Materials", "fhlibrarym.asp", "", 265);
admi("", "", "", 265, "hr.gif");
admi("Enchantments", "fhlibrarye.asp", "", 265);
admi("Trading Cards", "fhlibraryc.asp", "", 265);
admi("Special Trophies", "fhlibrarystro.asp", "", 265);
admi("Trophy Relics", "fhlibrarystror.asp", "", 265);
admi("Buildings", "fhlibraryb.asp", "", 230);
admi("Spells", "fhlibrarysp.asp", "", 230);
admi("Styles", "fhlibraryst.asp", "", 230);
admi("Skills", "fhlibrarysk.asp", "", 230);
admi("Discoveries", "fhlibraryds.asp", "", 230);
adsm("Quests", "fhlibraryq.asp", "", 230);
admi("Allegiance Quests", "fhlibraryqa.asp", "", 286);
admi("General Quests", "fhlibraryq.asp", "", 286);
admi("Guild Quests", "fhlibrarygq.asp", "", 286);
admi("Trophy Quests", "fhlibraryqt.asp", "", 286);
admi("Vessel Quests", "fhlibraryqv.asp", "", 286);
admi("Disguises", "fhlibrarydis.asp", "", 230);
admi("Scrapbooks", "fhlibraryscrap.asp", "", 230);
admi("Allegiances", "fhlibraryal.asp", "", 230);
admi("Factions", "fhlibraryf.asp", "", 230);
adsm("World", "forums/maps.asp", "_blank", 230);
admi("Maps", "forums/maps.asp", "_blank", 296);
admi("", "", "", 230, "hr.gif");
admi("Advanced Search", "fhsearcha.asp", "", 230);
adsm("Help", "https://guide.landsofhope.com/help", "", null);
adsm("Manual", "manualnew.asp", "_blank", 300);
admi("Knotwood Valley", "https://guide.landsofhope.com/World/10", "_blank", 301);
admi("Sandydale Basin", "https://guide.landsofhope.com/World/7", "_blank", 301);
admi("Riverscape", "https://guide.landsofhope.com/World/8", "_blank", 301);
admi("Barren Downs", "https://guide.landsofhope.com/World/9", "_blank", 301);
admi("Lakeview", "https://guide.landsofhope.com/World/6", "_blank", 301);
admi("Three Glaciers", "https://guide.landsofhope.com/World/4", "_blank", 301);
admi("Coldbreeze", "https://guide.landsofhope.com/World/3", "_blank", 301);
admi("Frostvale", "https://guide.landsofhope.com/World/2", "_blank", 301);
admi("Seven Sisters", "https://guide.landsofhope.com/World/5", "_blank", 301);
admi("Royal Hollow", "https://guide.landsofhope.com/World/1", "_blank", 301);
admi("", "", "", 301, "hr.gif");
admi("Juratania", "https://guide.landsofhope.com/World/13", "_blank", 301);
admi("Shrouded Islands", "https://guide.landsofhope.com/World/14", "_blank", 301);
admi("Eternal Plains", "https://guide.landsofhope.com/World/16", "_blank", 301);
admi("Eastern Lands", "https://guide.landsofhope.com/World/17", "_blank", 301);
admi("Demonic Plains", "https://guide.landsofhope.com/World/18", "_blank", 301);
admi("The Underworld", "https://guide.landsofhope.com/World/19", "_blank", 301);
admi("Heavenly Arena", "https://guide.landsofhope.com/World/20", "_blank", 301);
admi("Walkthrough", "https://guide.landsofhope.com/start/", "_blank", 300);
admi("", "", "", 300, "hr.gif");
admi("FAQ Topics", "https://guide.landsofhope.com/faqs", "", 300);
admi("", "", "", 300, "hr.gif");
admi("Help Topics", "https://guide.landsofhope.com/help", "", 300);
admi("", "", "", 300, "hr.gif");
admi("Ideas", "fhfeature.asp", "", 300);
admi("Submit Idea", "fhsubmit.asp", "", 300);
admi("Idea search", "fhfeatures.asp", "", 300);
admi("", "", "", 300, "hr.gif");
admi("Report Bug", "fhbugn.asp", "", 300);
admi("View Bug", "fhbug.asp", "", 300);
admi("", "", "", 300, "hr.gif");
admi("Forums", "forums/", "_blank", 300);
admi("Website", "http://www.landsofhope.com", "_blank", 300);
admi("Surveys", "fhsurvey.asp", "", 300);
admi("Email Support", "mailto:support@landsofhope.com", "", 300);
reloadmenu();
