UnloadMenu();
adsm("File", "fhcharc.asp", "", null);
admi("Logout", "fhlogout.asp", "", 1);
adsm("World", "fh.asp", "", null);
admi("World", "worldmap.asp", "", 3);
adsm("Maps", "map.asp", "", 3);
admi("", "", "", 5, "hr.gif");
admi("Treasure", "map2.asp", "", 5);
admi("", "", "", 5, "hr.gif");
admi("Keeps", "mapkeep.asp", "", 5, " ");
admi("Artifacts", "artifacts.asp", "", 5, " ");
admi("Territory", "mappirate.asp", "", 5, " ");
adsm("Reveal", "fhreveal.asp", "", 3);
admi("Players", "fhreveal.asp", "", 12);
admi("Property", "fhrevealb.asp", "", 12);
admi("", "", "", 3, "hr.gif");
admi("Travel", "fhfav.asp?Test=A", "", 3);
admi("Mark", "fh.asp?Mark=1", "", 3);
admi("", "", "", 3, "hr.gif");
admi("Make Portal", "fhmp.asp", "", 3);
admi("Open Portal", "fhpor.asp", "", 3);
admi("", "", "", 3, "hr.gif");
admi("Landmarks", "fhland.asp", "", 3);
admi("Challenges", "fhchallenges.asp", "", 3);
admi("Dungeons", "fhlandd.asp", "", 3);
admi("", "", "", 3, "hr.gif");
admi("Rest", "fhrest.asp?Test=A", "", 3);
adsm("Inventory", "fhInv.asp?InventoryItemID=1&ItemTypeID=1", "", null);
admi("Crafting Supplies", "fhinv.asp?F=-1", "", 27);
adsm("Main Tradeskills", "fhcraft.asp", "", 27);
admi("Alchemy", "fhmake2.asp?SkillID=26", "", 29);
admi("Blacksmithing", "fhmake2.asp?SkillID=25", "", 29);
admi("Carpentry", "fhmake2.asp?SkillID=23", "", 29);
admi("Construction", "fhmake2.asp?SkillID=32", "", 29);
admi("Cooking", "fhmake2.asp?SkillID=59", "", 29);
admi("Dungeon Mastery", "fhmake2.asp?SkillID=27", "", 29);
admi("Floristry", "fhmake2.asp?SkillID=189", "", 29);
admi("Furnishing", "fhmake2.asp?SkillID=140", "", 29);
admi("Leatherworking", "fhmake2.asp?SkillID=17", "", 29);
admi("Stonemasonry", "fhmake2.asp?SkillID=63", "", 29);
admi("Tailoring", "fhmake2.asp?SkillID=58", "", 29);
admi("Tinkering", "fhmake2.asp?SkillID=28", "", 29);
adsm("Class Tradeskills", "fhcraft.asp", "", 27);
admi("Animation", "fhmake2.asp?SkillID=180", "", 42);
admi("Artisan", "fhmake2.asp?SkillID=109", "", 42);
admi("Bewitching", "fhmake2.asp?SkillID=196", "", 42);
admi("Charms", "fhmake2.asp?SkillID=195", "", 42);
admi("Lordship", "fhmake2.asp?SkillID=202", "", 42);
admi("Parlor Tricks", "fhmake2.asp?SkillID=200", "", 42);
admi("Patchcrafting", "fhmake2.asp?SkillID=83", "", 42);
admi("Seamanship", "fhmake2.asp?SkillID=64", "", 42);
admi("Surgery", "fhmake2.asp?SkillID=107", "", 42);
admi("", "", "", 42, "hr.gif");
admi("Bejeweling", "fhbejewel.asp", "", 42);
admi("Grenades", "fhgrenade.asp", "", 42);
admi("Poisoning", "fhpoison.asp", "", 42);
admi("Subterfuge", "fhsubterfuge.asp", "", 42);
admi("Trap", "fhtrap.asp", "", 42);
adsm("Other Tradeskills", "fhcraft.asp", "", 27);
admi("Inscription", "fhinscribe.asp", "", 58);
adsm("Containers", "fhinv.asp?InventoryItemID=1&ItemTypeID=1", "", 27);
admi("All", "fhinv.asp?InventoryItemID=1&ItemTypeID=1", "", 60);
admi("Backpack", "fhinv.asp?InventoryItemID=1&ItemTypeID=6", "", 60);
admi("Sell Bag", "fhinv.asp?InventoryItemID=1&ItemTypeID=67", "", 60);
admi("Equipped", "fhinv.asp?InventoryItemID=1&ItemTypeID=-1", "", 60);
admi("Trade Bag", "fhtb.asp", "", 60);
admi("Bags", "fhbags.asp", "", 60);
admi("", "", "", 60, "hr.gif");
admi("Maps", "fhinvm.asp", "", 60);
admi("Books", "fhbook.asp", "", 60);
admi("Keys", "fhkey.asp", "", 60);
admi("Equipment", "fhequip.asp", "", 27);
adsm("Expansion Items", "fhinv.asp?F=23", "", 27);
admi("Jurassic Wars", "fhinv.asp?F=23", "", 72);
admi("Uncharted Waters", "fhinv.asp?F=24", "", 72);
admi("Dragons of the East", "fhinv.asp?F=25", "", 72);
admi("Afterlife", "fhinv.asp?F=26", "", 72);
admi("Dark Depths", "fhinv.asp?F=27", "", 72);
adsm("Auctions", "fhauc.asp", "", 27);
admi("All Auctions", "fhauc.asp", "", 78);
admi("Browse", "fhauc2.asp", "", 78);
admi("Comments", "fhauco.asp", "", 78);
admi("", "", "", 78, "hr.gif");
admi("Your Bids", "fhaucb.asp", "", 78);
admi("", "", "", 78, "hr.gif");
admi("Add Auction", "fhauca.asp", "", 78);
admi("Edit Auction", "fhauce.asp", "", 78);
admi("Manage", "fhaucm.asp", "", 78);
admi("", "", "", 78, "hr.gif");
admi("Completed", "fhaucmc.asp", "", 78);
adsm("Actions", "fhunlock.asp", "", 27);
admi("Price", "fhvalue.asp?InventoryItemID=1&ItemTypeID=1", "", 90);
admi("Flags", "fhIFlag.asp?InventoryItemID=1&ItemTypeID=1", "", 90);
admi("Consume", "fheat.asp?InventoryItemID=1", "", 90);
admi("Ready Items", "fhiready.asp", "", 90);
admi("Transmogrify", "fhtransmogrify.asp", "", 90);
admi("", "", "", 90, "hr.gif");
admi("Split", "fhsplit.asp", "", 90);
admi("Stack", "fhstack.asp", "", 90);
admi("Drop", "fhIDrop.asp?InventoryItemID=1&ItemTypeID=1", "", 90);
admi("Disguise", "fhdeception.asp?InventoryItemID=1&ItemTypeID=1", "", 90);
admi("Dismantle", "fhdis.asp?InventoryItemID=1&ItemTypeID=1", "", 90);
admi("", "", "", 90, "hr.gif");
admi("Unlock", "fhunlock.asp", "", 90);
admi("Uncover", "fharch.asp", "", 90);
admi("", "", "", 27, "hr.gif");
admi("Spells", "fhispells.asp", "", 27);
admi("Bonuses", "fhextrai.asp", "", 27);
admi("Bejeweling", "fhinvbejewel.asp", "", 27);
admi("Bewitching", "fhbewitch.asp", "", 27);
admi("Patches", "fhinvpatch.asp", "", 27);
admi("Puzzle", "fhipuzzle.asp", "", 27);
admi("Sets", "fhsspells.asp", "", 27);
admi("", "", "", 27, "hr.gif");
admi("Queue", "fhqueue.asp?Type=AA", "", 27);
adsm("Character", "fhstat.asp", "", null);
admi("Info", "fhstat.asp", "", 115);
admi("Skills", "fhskill.asp?B=&T=AA", "", 115);
admi("Storage", "fhstor.asp", "", 115);
admi("Duels", "fhduelstatus.asp", "", 115);
admi("Trade", "fhtrade.asp", "", 115);
adsm("Statistics", "fhsales.asp", "", 115);
admi("Kills", "fhkills.asp", "", 121);
admi("", "", "", 115, "hr.gif");
admi("", "", "", 115, "hr.gif");
admi("Messages", "fhmess.asp?Type=AA", "", 115);
admi("", "", "", 115, "hr.gif");
admi("Shortcuts", "fhmacro.asp?G=0", "", 115);
admi("Responses", "fhresp.asp", "", 115);
admi("", "", "", 115, "hr.gif");
admi("Appearance Profile", "fhcharxcp.asp", "", 115);
adsm("Abilities", "fhstyles.asp", "", null);
admi("Styles", "fhstyles.asp", "", 131);
admi("Ready Styles", "fhstylese.asp", "", 131);
admi("", "", "", 131, "hr.gif");
admi("Spellbook", "fhspells.asp", "", 131);
admi("Ready Spell", "fhspellse.asp", "", 131);
admi("Active", "fhaspells.asp", "", 131);
admi("", "", "", 131, "hr.gif");
admi("Allegiance", "fhals.asp", "", 131);
adsm("Property", "fhBM.asp", "", null);
adsm("Manage", "fhbm.asp", "", 140);
admi("All", "fhbm.asp", "", 141);
admi("Owned", "fhbm.asp?Filter=2", "", 141);
admi("Managed", "fhbm.asp?Filter=3", "", 141);
admi("", "", "", 140, "hr.gif");
admi("Build Deed", "fhmake2.asp?SkillID=32", "", 140);
admi("Build Dungeon", "fhmake2.asp?SkillID=27", "", 140);
adsm("Library", "fhlibraryr.asp", "", null);
adsm("Rankings", "rankings.asp", "_blank", 148);
admi("Wanted Criminals", "fhcriminals.asp", "", 149);
admi("Player vs Player", "pvpstandings.asp", "_blank", 149);
admi("", "", "", 148, "hr.gif");
adsm("Races", "fhlibraryr.asp", "", 148);
admi("Races", "fhlibraryr.asp", "", 153);
admi("Race Evolution", "fhlibraryre.asp", "", 153);
admi("Tameable Races", "fhlibraryrt.asp", "", 153);
admi("", "", "", 153, "hr.gif");
admi("Dungeon Spawns", "fhlibraryrd.asp", "", 153);
admi("Mounts", "fhlibraryrm.asp", "", 153);
adsm("Professions", "fhlibraryp.asp", "", 148);
admi("Professions", "fhlibraryp.asp", "", 160);
admi("Profession Evolution", "fhlibrarype.asp", "", 160);
adsm("Uncharted Waters", "fhlibraryv.asp", "", 148);
admi("Vessels", "fhlibraryv.asp", "", 163);
admi("Vessel Items", "fhlibraryvi.asp", "", 163);
admi("Expansion Items", "fhlibraryiex.asp?E=2", "", 163);
admi("Bejeweling", "fhlibrarybj.asp", "", 163);
adsm("Jurassic Wars", "", "", 148);
admi("Expansion Items", "fhlibraryiex.asp?E=1", "", 168);
adsm("Dragons of the East", "", "", 148);
admi("Dragon Factions", "fhlibrarydragp.asp", "", 170);
admi("Expansion Items", "fhlibraryiex.asp?E=3", "", 170);
adsm("The Afterlife", "", "", 148);
admi("Quests", "fhlibraryqt.asp?SN=&CharsAt=19&P=1", "", 173);
admi("Expansion Items", "fhlibraryiex.asp?E=4", "", 173);
admi("Bewitching", "fhlibrarypl2.asp?Type=BEWITCHING", "", 173);
admi("Charms", "fhlibrarypl2.asp?Type=CHARMS AND HEXES", "", 173);
admi("Hexes", "fhlibrarysp2.asp?CharsAt=195&SN=CHARMS AND HEXES", "", 173);
adsm("Dark Depths", "", "", 148);
admi("Expansion Items", "fhlibraryiex.asp?E=5", "", 179);
admi("", "", "", 148, "hr.gif");
adsm("Items", "fhlibraryi.asp", "", 148);
admi("Sets", "fhlibraryset.asp", "", 182);
admi("", "", "", 182, "hr.gif");
admi("Plans", "fhlibrarypl.asp", "", 182);
admi("Items", "fhlibraryi.asp", "", 182);
admi("Armor", "fhlibrarya.asp", "", 182);
admi("Tools", "fhlibraryit.asp", "", 182);
admi("Weapons", "fhlibraryw.asp", "", 182);
admi("Siege Weapons", "fhlibrarysw.asp", "", 182);
admi("Steal Loot", "fhlibraryisl.asp", "", 182);
admi("Materials", "fhlibrarym.asp", "", 182);
admi("", "", "", 182, "hr.gif");
admi("Enchantments", "fhlibrarye.asp", "", 182);
admi("Trading Cards", "fhlibraryc.asp", "", 182);
admi("Special Trophies", "fhlibrarystro.asp", "", 182);
admi("Trophy Relics", "fhlibrarystror.asp", "", 182);
admi("Buildings", "fhlibraryb.asp", "", 148);
admi("Spells", "fhlibrarysp.asp", "", 148);
admi("Styles", "fhlibraryst.asp", "", 148);
admi("Skills", "fhlibrarysk.asp", "", 148);
admi("Discoveries", "fhlibraryds.asp", "", 148);
adsm("Quests", "fhlibraryq.asp", "", 148);
admi("Allegiance Quests", "fhlibraryqa.asp", "", 203);
admi("General Quests", "fhlibraryq.asp", "", 203);
admi("Guild Quests", "fhlibrarygq.asp", "", 203);
admi("Trophy Quests", "fhlibraryqt.asp", "", 203);
admi("Vessel Quests", "fhlibraryqv.asp", "", 203);
admi("Disguises", "fhlibrarydis.asp", "", 148);
admi("Scrapbooks", "fhlibraryscrap.asp", "", 148);
admi("Allegiances", "fhlibraryal.asp", "", 148);
admi("Factions", "fhlibraryf.asp", "", 148);
adsm("World", "forums/maps.asp", "_blank", 148);
admi("Maps", "forums/maps.asp", "_blank", 213);
admi("", "", "", 148, "hr.gif");
admi("Advanced Search", "fhsearcha.asp", "", 148);
adsm("Help", "https://guide.landsofhope.com/help", "", null);
adsm("Manual", "manualnew.asp", "_blank", 217);
admi("Knotwood Valley", "https://guide.landsofhope.com/World/10", "_blank", 218);
admi("Sandydale Basin", "https://guide.landsofhope.com/World/7", "_blank", 218);
admi("Riverscape", "https://guide.landsofhope.com/World/8", "_blank", 218);
admi("Barren Downs", "https://guide.landsofhope.com/World/9", "_blank", 218);
admi("Lakeview", "https://guide.landsofhope.com/World/6", "_blank", 218);
admi("Three Glaciers", "https://guide.landsofhope.com/World/4", "_blank", 218);
admi("Coldbreeze", "https://guide.landsofhope.com/World/3", "_blank", 218);
admi("Frostvale", "https://guide.landsofhope.com/World/2", "_blank", 218);
admi("Seven Sisters", "https://guide.landsofhope.com/World/5", "_blank", 218);
admi("Royal Hollow", "https://guide.landsofhope.com/World/1", "_blank", 218);
admi("", "", "", 218, "hr.gif");
admi("Juratania", "https://guide.landsofhope.com/World/13", "_blank", 218);
admi("Shrouded Islands", "https://guide.landsofhope.com/World/14", "_blank", 218);
admi("Eternal Plains", "https://guide.landsofhope.com/World/16", "_blank", 218);
admi("Eastern Lands", "https://guide.landsofhope.com/World/17", "_blank", 218);
admi("Demonic Plains", "https://guide.landsofhope.com/World/18", "_blank", 218);
admi("The Underworld", "https://guide.landsofhope.com/World/19", "_blank", 218);
admi("Heavenly Arena", "https://guide.landsofhope.com/World/20", "_blank", 218);
admi("Walkthrough", "https://guide.landsofhope.com/start/", "_blank", 217);
admi("", "", "", 217, "hr.gif");
admi("FAQ Topics", "https://guide.landsofhope.com/faqs", "", 217);
admi("", "", "", 217, "hr.gif");
admi("Help Topics", "https://guide.landsofhope.com/help", "", 217);
admi("", "", "", 217, "hr.gif");
admi("Ideas", "fhfeature.asp", "", 217);
admi("Submit Idea", "fhsubmit.asp", "", 217);
admi("Idea search", "fhfeatures.asp", "", 217);
admi("", "", "", 217, "hr.gif");
admi("Report Bug", "fhbugn.asp", "", 217);
admi("View Bug", "fhbug.asp", "", 217);
admi("", "", "", 217, "hr.gif");
admi("Forums", "forums/", "_blank", 217);
admi("Website", "http://www.landsofhope.com", "_blank", 217);
admi("Surveys", "fhsurvey.asp", "", 217);
admi("Email Support", "mailto:support@landsofhope.com", "", 217);
reloadmenu();
