UnloadMenu();
adsm("File", "fhcharc.asp", "", null);
admi("Calendar", "fhcal.asp", "", 1);
admi("Links", "fhurl.asp", "", 1);
admi("Buy Extras", "fhcharx.asp", "", 1);
admi("", "", "", 1, "hr.gif");
admi("Options", "fhoption.asp?G=0", "", 1);
admi("Chat Options", "fhoption.asp?Group=Chat", "", 1);
admi("Logout", "fhlogout.asp", "", 1);
adsm("World", "fh.asp", "", null);
adsm("Maps", "map.asp", "", 9);
admi("NPC Locations", "mapnpc.asp", "_blank", 10);
admi("", "", "", 10, "hr.gif");
admi("", "", "", 9, "hr.gif");
admi("Travel", "fhfav.asp?Test=A", "", 9);
admi("Mark", "fh.asp?Mark=1", "", 9);
admi("", "", "", 9, "hr.gif");
admi("Rest", "fhrest.asp?Test=A", "", 9);
adsm("Inventory", "fhInv.asp?InventoryItemID=1&ItemTypeID=1", "", null);
adsm("Containers", "fhinv.asp?InventoryItemID=1&ItemTypeID=1", "", 18);
admi("All", "fhinv.asp?InventoryItemID=1&ItemTypeID=1", "", 19);
admi("Backpack", "fhinv.asp?InventoryItemID=1&ItemTypeID=6", "", 19);
admi("Sell Bag", "fhinv.asp?InventoryItemID=1&ItemTypeID=67", "", 19);
admi("Trade Bag", "fhtb.asp", "", 19);
admi("Bags", "fhbags.asp", "", 19);
admi("", "", "", 19, "hr.gif");
admi("Maps", "fhinvm.asp", "", 19);
admi("Books", "fhbook.asp", "", 19);
admi("Keys", "fhkey.asp", "", 19);
admi("Equipment", "fhequip.asp", "", 18);
adsm("Auctions", "fhauc.asp", "", 18);
admi("All Auctions", "fhauc.asp", "", 30);
admi("Browse", "fhauc2.asp", "", 30);
admi("Comments", "fhauco.asp", "", 30);
admi("", "", "", 30, "hr.gif");
admi("Your Bids", "fhaucb.asp", "", 30);
admi("", "", "", 30, "hr.gif");
admi("Add Auction", "fhauca.asp", "", 30);
admi("Edit Auction", "fhauce.asp", "", 30);
admi("Manage", "fhaucm.asp", "", 30);
admi("", "", "", 30, "hr.gif");
admi("Completed", "fhaucmc.asp", "", 30);
admi("", "", "", 18, "hr.gif");
admi("Spells", "fhispells.asp", "", 18);
admi("Bonuses", "fhextrai.asp", "", 18);
admi("", "", "", 18, "hr.gif");
admi("Queue", "fhqueue.asp?Type=AA", "", 18);
adsm("Character", "fhstat.asp", "", null);
admi("Info", "fhstat.asp", "", 47);
admi("Skills", "fhskill.asp?B=&T=AA", "", 47);
admi("Jobs", "fhwant.asp", "", 47);
admi("Storage", "fhstor.asp", "", 47);
admi("Mount Bonuses", "fhmount.asp", "", 47);
admi("Trade", "fhtrade.asp", "", 47);
adsm("Statistics", "fhsales.asp", "", 47);
admi("Kills", "fhkills.asp", "", 54);
admi("", "", "", 47, "hr.gif");
admi("Fellowships", "fhgroups.asp", "", 47);
admi("", "", "", 47, "hr.gif");
admi("Quests", "fhquest.asp?Type=AA", "", 47);
admi("", "", "", 47, "hr.gif");
admi("Friends", "fhfriend.asp?Type=AA", "", 47);
admi("Messages", "fhmess.asp?Type=AA", "", 47);
admi("", "", "", 47, "hr.gif");
admi("Shortcuts", "fhmacro.asp?G=0", "", 47);
admi("Responses", "fhresp.asp", "", 47);
adsm("Abilities", "fhstyles.asp", "", null);
admi("Spellbook", "fhspells.asp", "", 66);
admi("Active", "fhaspells.asp", "", 66);
adsm("Guilds", "fhguilds.asp", "", null);
admi("View", "fhguilds.asp", "", 69);
admi("", "", "", 69, "hr.gif");
admi("Manage / Create", "fhgum.asp", "", 69);
admi("", "", "", 69, "hr.gif");
admi("Roster", "fhgur.asp", "", 69);
admi("Messages", "fhgume.asp", "", 69);
admi("Property", "fhguildsp.asp", "", 69);
adsm("Minions", "fhminions.asp", "", null);
adsm("Manage", "fhminions.asp", "", 77);
admi("Tamed", "fhminions.asp?H=1", "", 78);
admi("Summons", "fhminions.asp?H=2", "", 78);
admi("Vendors", "fhminions.asp?H=3", "", 78);
admi("NPCs", "fhmnpc.asp", "", 78);
admi("", "", "", 78, "hr.gif");
admi("Possess", "fhmip.asp", "", 77);
admi("Shopkeep Trade", "fhtpop.asp", "", 77);
admi("Dismiss", "fhminionsd.asp", "", 77);
admi("Mounts", "fhmim.asp", "", 77);
admi("", "", "", 77, "hr.gif");
adsm("Breeding", "fhbreed.asp", "", 77);
admi("Breeding Queue", "fhmq.asp", "", 89);
adsm("Property", "fhBM.asp", "", null);
admi("Manage", "fhbm.asp", "", 91);
admi("Trade", "fhBgt.asp", "", 91);
admi("", "", "", 91, "hr.gif");
admi("Build Deed", "fhmake2.asp?SkillID=32", "", 91);
admi("Build Dungeon", "fhmake2.asp?SkillID=27", "", 91);
adsm("Library", "fhlibraryr.asp", "", null);
adsm("Rankings", "rankings.asp", "_blank", 97);
admi("Wanted Criminals", "fhcriminals.asp", "", 98);
admi("", "", "", 97, "hr.gif");
admi("", "", "", 97, "hr.gif");
admi("Spells", "fhlibrarysp.asp", "", 97);
admi("Styles", "fhlibraryst.asp", "", 97);
admi("Discoveries", "fhlibraryds.asp", "", 97);
admi("", "", "", 97, "hr.gif");
admi("Advanced Search", "fhsearcha.asp", "", 97);
adsm("Help", "https://guide.landsofhope.com/help", "", null);
admi("Help Topics", "https://guide.landsofhope.com/help", "", 107);
admi("", "", "", 107, "hr.gif");
admi("Ideas", "fhfeature.asp", "", 107);
admi("Submit Idea", "fhsubmit.asp", "", 107);
admi("", "", "", 107, "hr.gif");
admi("Report Bug", "fhbugn.asp", "", 107);
admi("View Bug", "fhbug.asp", "", 107);
admi("", "", "", 107, "hr.gif");
admi("Forums", "forums/", "_blank", 107);
admi("Website", "http://www.landsofhope.com", "_blank", 107);
admi("Email Support", "mailto:support@landsofhope.com", "", 107);
reloadmenu();
