var selectedcountry = 'US';


function drawcountries(selcountry) {
selectedcountry = selcountry;
adp('CA','CANADA');
adp('GB','UNITED KINGDOM');
adp('US','UNITED STATES');
adp('AF','AFGHANISTAN');
adp('AX','ÅLAND ISLANDS');
adp('AL','ALBANIA');
adp('DZ','ALGERIA');
adp('AS','AMERICAN SAMOA');
adp('AD','ANDORRA');
adp('AO','ANGOLA');
adp('AI','ANGUILLA');
adp('AQ','ANTARCTICA');
adp('AG','ANTIGUA AND BARBUDA');
adp('AR','ARGENTINA');
adp('AM','ARMENIA');
adp('AW','ARUBA');
adp('AU','AUSTRALIA');
adp('AT','AUSTRIA');
adp('AZ','AZERBAIJAN');
adp('BS','BAHAMAS');
adp('BH','BAHRAIN');
adp('BD','BANGLADESH');
adp('BB','BARBADOS');
adp('BY','BELARUS');
adp('BE','BELGIUM');
adp('BZ','BELIZE');
adp('BJ','BENIN');
adp('BM','BERMUDA');
adp('BT','BHUTAN');
adp('BO','BOLIVIA');
adp('BA','BOSNIA AND HERZEGOVINA');
adp('BW','BOTSWANA');
adp('BV','BOUVET ISLAND');
adp('BR','BRAZIL');
adp('IO','BRITISH INDIAN OCEAN TERRITORY');
adp('BN','BRUNEI DARUSSALAM');
adp('BG','BULGARIA');
adp('BF','BURKINA FASO');
adp('BI','BURUNDI');
adp('KH','CAMBODIA');
adp('CM','CAMEROON');
adp('CV','CAPE VERDE');
adp('KY','CAYMAN ISLANDS');
adp('CF','CENTRAL AFRICAN REPUBLIC');
adp('TD','CHAD');
adp('CL','CHILE');
adp('CN','CHINA');
adp('CX','CHRISTMAS ISLAND');
adp('CC','COCOS (KEELING) ISLANDS');
adp('CO','COLOMBIA');
adp('KM','COMOROS');
adp('CG','CONGO');
adp('CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE');
adp('CK','COOK ISLANDS');
adp('CR','COSTA RICA');
adp('CI','CÔTE D`IVOIRE');
adp('HR','CROATIA');
adp('CU','CUBA');
adp('CY','CYPRUS');
adp('CZ','CZECH REPUBLIC');
adp('DK','DENMARK');
adp('DJ','DJIBOUTI');
adp('DM','DOMINICA');
adp('DO','DOMINICAN REPUBLIC');
adp('EC','ECUADOR');
adp('EG','EGYPT');
adp('SV','EL SALVADOR');
adp('GQ','EQUATORIAL GUINEA');
adp('ER','ERITREA');
adp('EE','ESTONIA');
adp('ET','ETHIOPIA');
adp('FK','FALKLAND ISLANDS (MALVINAS)');
adp('FO','FAROE ISLANDS');
adp('FJ','FIJI');
adp('FI','FINLAND');
adp('FR','FRANCE');
adp('GF','FRENCH GUIANA');
adp('PF','FRENCH POLYNESIA');
adp('TF','FRENCH SOUTHERN TERRITORIES');
adp('GA','GABON');
adp('GM','GAMBIA');
adp('GE','GEORGIA');
adp('DE','GERMANY');
adp('GH','GHANA');
adp('GI','GIBRALTAR');
adp('GR','GREECE');
adp('GL','GREENLAND');
adp('GD','GRENADA');
adp('GP','GUADELOUPE');
adp('GU','GUAM');
adp('GT','GUATEMALA');
adp('GN','GUINEA');
adp('GW','GUINEA-BISSAU');
adp('GY','GUYANA');
adp('HT','HAITI');
adp('HM','HEARD ISLAND AND MCDONALD ISLANDS');
adp('VA','HOLY SEE (VATICAN CITY STATE)');
adp('HN','HONDURAS');
adp('HK','HONG KONG');
adp('HU','HUNGARY');
adp('IS','ICELAND');
adp('IN','INDIA');
adp('ID','INDONESIA');
adp('IR','IRAN, ISLAMIC REPUBLIC OF');
adp('IQ','IRAQ');
adp('IE','IRELAND');
adp('IL','ISRAEL');
adp('IT','ITALY');
adp('JM','JAMAICA');
adp('JP','JAPAN');
adp('JO','JORDAN');
adp('KZ','KAZAKHSTAN');
adp('KE','KENYA');
adp('KI','KIRIBATI');
adp('KP','KOREA, DEMOCRATIC PEOPLE`S REPUBLIC OF');
adp('KR','KOREA, REPUBLIC OF');
adp('KW','KUWAIT');
adp('KG','KYRGYZSTAN');
adp('LA','LAO PEOPLE`S DEMOCRATIC REPUBLIC');
adp('LV','LATVIA');
adp('LB','LEBANON');
adp('LS','LESOTHO');
adp('LR','LIBERIA');
adp('LY','LIBYAN ARAB JAMAHIRIYA');
adp('LI','LIECHTENSTEIN');
adp('LT','LITHUANIA');
adp('LU','LUXEMBOURG');
adp('MO','MACAO');
adp('MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF');
adp('MG','MADAGASCAR');
adp('MW','MALAWI');
adp('MY','MALAYSIA');
adp('MV','MALDIVES');
adp('ML','MALI');
adp('MT','MALTA');
adp('MH','MARSHALL ISLANDS');
adp('MQ','MARTINIQUE');
adp('MR','MAURITANIA');
adp('MU','MAURITIUS');
adp('YT','MAYOTTE');
adp('MX','MEXICO');
adp('FM','MICRONESIA, FEDERATED STATES OF');
adp('MD','MOLDOVA, REPUBLIC OF');
adp('MC','MONACO');
adp('MN','MONGOLIA');
adp('MS','MONTSERRAT');
adp('MA','MOROCCO');
adp('MZ','MOZAMBIQUE');
adp('MM','MYANMAR');
adp('NA','NAMIBIA');
adp('NR','NAURU');
adp('NP','NEPAL');
adp('NL','NETHERLANDS');
adp('AN','NETHERLANDS ANTILLES');
adp('NC','NEW CALEDONIA');
adp('NZ','NEW ZEALAND');
adp('NI','NICARAGUA');
adp('NE','NIGER');
adp('NG','NIGERIA');
adp('NU','NIUE');
adp('NF','NORFOLK ISLAND');
adp('MP','NORTHERN MARIANA ISLANDS');
adp('NO','NORWAY');
adp('OM','OMAN');
adp('PK','PAKISTAN');
adp('PW','PALAU');
adp('PS','PALESTINIAN TERRITORY, OCCUPIED');
adp('PA','PANAMA');
adp('PG','PAPUA NEW GUINEA');
adp('PY','PARAGUAY');
adp('PE','PERU');
adp('PH','PHILIPPINES');
adp('PN','PITCAIRN');
adp('PL','POLAND');
adp('PT','PORTUGAL');
adp('PR','PUERTO RICO');
adp('QA','QATAR');
adp('RE','RÉUNION');
adp('RO','ROMANIA');
adp('RU','RUSSIAN FEDERATION');
adp('RW','RWANDA');
adp('SH','SAINT HELENA');
adp('KN','SAINT KITTS AND NEVIS');
adp('LC','SAINT LUCIA');
adp('PM','SAINT PIERRE AND MIQUELON');
adp('VC','SAINT VINCENT AND THE GRENADINES');
adp('WS','SAMOA');
adp('SM','SAN MARINO');
adp('ST','SAO TOME AND PRINCIPE');
adp('SA','SAUDI ARABIA');
adp('SN','SENEGAL');
adp('CS','SERBIA AND MONTENEGRO');
adp('SC','SEYCHELLES');
adp('SL','SIERRA LEONE');
adp('SG','SINGAPORE');
adp('SK','SLOVAKIA');
adp('SI','SLOVENIA');
adp('SB','SOLOMON ISLANDS');
adp('SO','SOMALIA');
adp('ZA','SOUTH AFRICA');
adp('GS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS');
adp('ES','SPAIN');
adp('LK','SRI LANKA');
adp('SD','SUDAN');
adp('SR','SURINAME');
adp('SJ','SVALBARD AND JAN MAYEN');
adp('SZ','SWAZILAND');
adp('SE','SWEDEN');
adp('CH','SWITZERLAND');
adp('SY','SYRIAN ARAB REPUBLIC');
adp('TW','TAIWAN');
adp('TJ','TAJIKISTAN');
adp('TZ','TANZANIA, UNITED REPUBLIC OF');
adp('TH','THAILAND');
adp('TL','TIMOR-LESTE');
adp('TG','TOGO');
adp('TK','TOKELAU');
adp('TO','TONGA');
adp('TT','TRINIDAD AND TOBAGO');
adp('TN','TUNISIA');
adp('TR','TURKEY');
adp('TM','TURKMENISTAN');
adp('TC','TURKS AND CAICOS ISLANDS');
adp('TV','TUVALU');
adp('UG','UGANDA');
adp('UA','UKRAINE');
adp('AE','UNITED ARAB EMIRATES');
adp('UM','UNITED STATES MINOR OUTLYING ISLANDS');
adp('UY','URUGUAY');
adp('UZ','UZBEKISTAN');
adp('VU','VANUATU');
adp('VE','VENEZUELA');
adp('VN','VIET NAM');
adp('VG','VIRGIN ISLANDS, BRITISH');
adp('VI','VIRGIN ISLANDS, U.S.');
adp('WF','WALLIS AND FUTUNA');
adp('EH','WESTERN SAHARA');
adp('YE','YEMEN');
adp('ZM','ZAMBIA');
adp('ZW','ZIMBABWE');
}

function adp(countrycode, countryname ) {
document.write('<option value=\'' + countrycode + '\' ' + (selectedcountry == countrycode ? 'selected' : '') + '>' + countryname + '</a>');
}