AddHelper('Map2','To get new spells after leaving the estate use the Help > Manual > Realm Name page to find the location of the relevant magic trainers for the skills you know.', 0, 'gold');
AddHelper('Interface','This is the fight screen, normally your character is on the left of the screen and your opponent on the right.', 0);
AddHelper('Inv','Your picture and stats show up on the left of the screen.', 1);
AddHelper('Inv2','Your opponents picture and stats show up on the right of the screen.', 1);
AddHelper('Fighter0','To take a turn select the fighter you wish to use (the first fighter is automatically selected).', 1, 'gold');
AddHelper('Buttons','In the middle of the screen is the list of actions you can try to perform, pretty much the same buttons show up for all characters.', 1);
AddHelper('Buttons','To perform a standard offensive magic attack click the Cast offensive spell button (first button on second row), to use a readied spell (Abilities > Ready Spells) use the second button.', 1);
AddHelper('Buttons','To use a defensive magic attack (primarily Healers) click the third or fourth buttons on the second row of buttons.', 1);
AddHelper('ResultsOfit','After taking a turn you will notice the fight results show up here, and your health or your enemies health will alter to display the changes.', 1);
AddHelper('ResultsOfit','Eventually when you or your opponent reaches 0 health the fight ends, if you won you will be taken to a loot screen otherwise you will become a ghost.', 1);
HelperB(0);