AddHelper('Map2','To get your starting styles go visit Guard Devon in the Garrison on the estate you will gain a Style book which can be used via the Inventory screen to gain styles.', 0, 'gold');
AddHelper('Interface','This is the fight screen, normally your character is on the left of the screen and your opponent on the right.', 0);
AddHelper('Inv','Your picture and stats show up on the left of the screen.', 1);
AddHelper('Inv2','Your opponents picture and stats show up on the right of the screen.', 1);
AddHelper('Fighter0','To take a turn select the fighter you wish to use (the first fighter is automatically selected).', 1, 'gold');
AddHelper('Buttons','In the middle of the screen is the list of actions you can try to perform, pretty much the same buttons show up for all characters.', 1);
AddHelper('Buttons','Although some characters will not have a use for all buttons. I.e. fighters do not get magic spells so the second row of buttons is irrelevant to them.', 1);
AddHelper('Buttons','To perform a standard melee attack click the Attack enemy button (first button on first row), to use a readied attack (Abilities > Ready Styles) use the second button.', 1);
AddHelper('Buttons','To use a ranged attack if you have a ranged weapon equipped such as a Bow click the ranged button (third or fourth buttons).', 1);
AddHelper('ResultsOfit','If you do not know any "styles" a basic default attack will be used, however if you know multiple styles you must manually pick one in the box at the bottom.', 1);
AddHelper('ResultsOfit','After taking a turn you will notice the fight results show up here, and your health or your enemies health will alter to display the changes.', 1);
AddHelper('ResultsOfit','Eventually when you or your opponent reaches 0 health the fight ends, if you won you will be taken to a loot screen otherwise you will become a ghost.', 1);
HelperB(0);