//var IPath = window.top.FHIP + "r/"

function DrawR() {
AVR(78, 'Alligator','mpalm.gif','mpalf.gif');
AVR(59, 'Angel','anm.gif','anf.gif');
AVR(358, 'Ankylosaur','ankm.gif','ankf.gif');
AVR(96, 'Annis','an1.gif','an2.gif');
AVR(350, 'Arachnins','aam.gif','aaf.gif');
AVR(282, 'Avalerion','xm.gif','xf.gif');
AVR(104, 'Banshee','mjpmas.gif','mjpfas.gif');
AVR(97, 'Barbegazi','ba1.gif','ba2.gif');
AVR(143, 'Basilisk','mpbam.gif','mpbaf.gif');
AVR(112, 'Bat','mpbatm.gif','mpbatf.gif');
AVR(114, 'Bear','br1.gif','b2.gif');
AVR(105, 'Behemoth','be2.gif','be1.gif');
AVR(63, 'Bird','bim.gif','bif.gif');
AVR(162, 'Biting nettle','mpbnm.gif','mpbnf.gif');
AVR(161, 'Bleeding fungus','mpbfm.gif','mpbfm.gif');
AVR(370, 'Bloodmaiden','mpblmm.gif','mpblmf.gif');
AVR(344, 'Bloodmaster','vlm.gif','vlf.gif');
AVR(137, 'Bloody reaper','mpbrm.gif','mpbrf.gif');
AVR(328, 'Bogles','mpbogm.gif','mpbogf.gif');
AVR(363, 'Bone dragon','bdm.gif','bdf.gif');
AVR(382, 'Boneguard','mjpmbg.gif','mjpfbg.gif');
AVR(132, 'Boogie man','mpbmm.gif','mpbmf.gif');
AVR(124, 'Camel','ca1.gif','ca2.gif');
AVR(126, 'Campire','mpcvm.gif','mpcvf.gif');
AVR(158, 'Carniverous ivy','mpcam.gif','mpcaf.gif');
AVR(40, 'Cat','mpcatm.gif','mpcatf.gif');
AVR(107, 'Centaur','com.gif','cof.gif');
AVR(108, 'Cerberus','cb1.gif','cb2.gif');
AVR(60, 'Chicken','chm.gif','chf.gif');
AVR(252, 'Cinder beast','mpcbm.gif','mpcbf.gif');
AVR(373, 'Cookie monster','mjcm.gif','mjcm.gif');
AVR(55, 'Cow','cm.gif','cf.gif');
AVR(153, 'Crab','mpcram.gif','mpcraf.gif');
AVR(166, 'Creeper','mpcrem.gif','mpcref.gif');
AVR(160, 'Creeping ivy','mpcim.gif','mpcif.gif');
AVR(164, 'Creeping weed','mpcrwm.gif','mpcrwf.gif');
AVR(79, 'Crocodile','mpcrm.gif','mpcrf.gif');
AVR(133, 'Cyclops','mpcym.gif','mpcyf.gif');
AVR(86, 'Darfurk','dam.gif','daf.gif');
AVR(202, 'Dark dwarf','ddm.gif','ddf.gif');
AVR(136, 'Dark reaper','mpdrm.gif','mpdrf.gif');
AVR(30, 'Deamon','da1.gif','da2.gif');
AVR(381, 'Deathcrawler','mjpmdc.gif','mjpfdc.gif');
AVR(352, 'Deathscarab','dsam.gif','dsaf.gif');
AVR(56, 'Deer','de2.gif','de4.gif');
AVR(300, 'Demorite','di1.gif','di2.gif');
AVR(325, 'Dinnshenchas','mpdim.gif','mpdif.gif');
AVR(39, 'Dog','mpdgm.gif','mpdgf.gif');
AVR(7, 'Dragon','sodrm5.gif','sodrf1.gif');
AVR(309, 'Dragonclan','dcm.gif','dcf.gif');
AVR(351, 'Dragonflyer','drafm.gif','draff.gif');
AVR(308, 'Dragonkin','dkm.gif','dkf.gif');
AVR(8, 'Drake','mpdra1.gif','mpdra7.gif');
AVR(22, 'Dread liche','dl1.gif','dl2.gif');
AVR(134, 'Drow','dom.gif','dof.gif');
AVR(326, 'Dryads','mpdym.gif','mpdyf.gif');
AVR(123, 'Duck','mpdum.gif','mpduf.gif');
AVR(277, 'Duergar','ddm.gif','ddf.gif');
AVR(101, 'Dummy','dy1.gif','dy2.gif');
AVR(88, 'Dwarf','dwm.gif','dwf.gif');
AVR(66, 'Eel','ee1.gif','ee2.gif');
AVR(11, 'Elder dragon','ed1.gif','ed2.gif');
AVR(35, 'Elder elemental','mpeem.gif','mpeef.gif');
AVR(23, 'Elder liche','el1.gif','el2.gif');
AVR(34, 'Elemental','mpelm.gif','mpelf.gif');
AVR(2, 'Elf','elm.gif','elf.gif');
AVR(110, 'Essence','mpesm.gif','mpesf.gif');
AVR(327, 'Fays','mpfam.gif','mpfaf.gif');
AVR(317, 'Feralkin','sofem1.gif','sofef1.gif');
AVR(338, 'Fiend','sm1.gif','sm2.gif');
AVR(64, 'Fish','fi1.gif','fi2.gif');
AVR(379, 'Fox','mjpmfx.gif','mjpffx.gif');
AVR(43, 'Fragment','mpfram.gif','mpfraf.gif');
AVR(76, 'Frog','fg1.gif','fg2.gif');
AVR(341, 'Fury','hgm.gif','hgf.gif');
AVR(4, 'Gelfling','gem.gif','gef.gif');
AVR(128, 'Genie','gim.gif','gif.gif');
AVR(340, 'Ghast','mppgam.gif','mppgaf.gif');
AVR(44, 'Ghost','ghm.gif','ghf.gif');
AVR(144, 'Ghoul','gum.gif','guf.gif');
AVR(332, 'Giant','smm.gif','smf.gif');
AVR(91, 'Giant beetle','mpgbm.gif','mpgbf.gif');
AVR(154, 'Giant crab','mpgcm.gif','mpgcf.gif');
AVR(77, 'Giant frog','gg1.gif','gg2.gif');
AVR(316, 'Giant octopus','oc1.gif','oc2.gif');
AVR(83, 'Giant rabbit','gt1.gif','gt2.gif');
AVR(147, 'Giant scorpion','mgism.gif','mpgisf.gif');
AVR(15, 'Giant spider','gr1.gif','gr2.gif');
AVR(339, 'Gibber','wi1.gif','wi2.gif');
AVR(330, 'Gnome','mpgnm.gif','mpgnf.gif');
AVR(58, 'Goat','mpgom.gif','mpgof.gif');
AVR(95, 'Goblin','mjpmgo.gif','mjpfgo.gif');
AVR(33, 'Golem','ge1.gif','ge2.gif');
AVR(93, 'Gorgon','gom.gif','gof.gif');
AVR(138, 'Grim reaper','mpgrm.gif','mpgrf.gif');
AVR(129, 'Gryphon','gfm.gif','gff.gif');
AVR(130, 'Gyrian','gym.gif','gyf.gif');
AVR(50, 'Hag','hgm.gif','hgf.gif');
AVR(5, 'Halfling','ham.gif','haf.gif');
AVR(16, 'Harpy','hpm.gif','hpf.gif');
AVR(141, 'Hellbeast','mphbm.gif','mphbf.gif');
AVR(347, 'Hellhound','mphhm.gif','mphhf.gif');
AVR(366, 'Hellish imp','mphim.gif','mphif.gif');
AVR(334, 'Hellspawn','da1.gif','da2.gif');
AVR(369, 'Hellwarden','mphwm.gif','mphwf.gif');
AVR(343, 'Horror','dl1.gif','dl2.gif');
AVR(54, 'Horse','hom.gif','hof.gif');
AVR(117, 'Hrrtani','hrm.gif','hrf.gif');
AVR(1, 'Human','hum.gif','huf.gif');
AVR(121, 'Hydra','mphym.gif','mphyf.gif');
AVR(87, 'Ice troll','il1.gif','il2.gif');
AVR(106, 'Imp','ipm.gif','ipf.gif');
AVR(150, 'Jackal','mpjkm.gif','mpjkf.gif');
AVR(156, 'Jellyfish','mpjfm.gif','mpjff.gif');
AVR(353, 'Killerwasp','kwm.gif','kwf.gif');
AVR(354, 'Ladybird','lbm.gif','lbf.gif');
AVR(9, 'Lemurian','lem.gif','lef.gif');
AVR(31, 'Lesser deamon','ld1.gif','ld2.gif');
AVR(20, 'Liche','li1.gif','li2.gif');
AVR(21, 'Liche lord','ll1.gif','ll2.gif');
AVR(368, 'Lifetaker','mpltm.gif','mpltf.gif');
AVR(152, 'Lion','mpliom.gif','mpliof.gif');
AVR(148, 'Lizard','mplizm.gif','mplizf.gif');
AVR(145, 'Lizardmen','mplmm.gif','mplmf.gif');
AVR(42, 'Lurcher','lc1.gif','lc2.gif');
AVR(119, 'Magnalian','mam.gif','maf.gif');
AVR(6, 'Maminal','mmm.gif','mmf.gif');
AVR(100, 'Mannequin','mpmaqm.gif','mpmaqf.gif');
AVR(364, 'Mantrap','manm.gif','manf.gif');
AVR(98, 'Mermaid','mjpmerm.gif','mjpmerf.gif');
AVR(131, 'Metal dragon','mnd.gif','mnd.gif');
AVR(380, 'Minotaur','mjpmm.gif','mjpmf.gif');
AVR(116, 'Moorlank','mom.gif','mof.gif');
AVR(38, 'Morphet','mo1.gif','mo2.gif');
AVR(17, 'Mummy','my1.gif','my2.gif');
AVR(52, 'Muncher','mu1.gif','mu2.gif');
AVR(13, 'Neanderthal','mpnem.gif','mpnef.gif');
AVR(103, 'Necrotic warrior','el1.gif','el2.gif');
AVR(319, 'Necryte','sozom1.gif','sozof1.gif');
AVR(99, 'Nereid','nem.gif','nef.gif');
AVR(268, 'Nightmare','mpnimm.gif','mpnimf.gif');
AVR(318, 'Nightstalker','srnsm1.gif','srnsf1.gif');
AVR(68, 'Octopus','oc1.gif','oc2.gif');
AVR(331, 'Ogre','mpogm.gif','mpogf.gif');
AVR(3, 'Orc','orm.gif','orf.gif');
AVR(28, 'Orc lord','ol2.gif','ol1.gif');
AVR(29, 'Orc warrior','ocm.gif','ocf.gif');
AVR(90, 'Pack horse','mppfm.gif','mpphf.gif');
AVR(267, 'Pegasus','mppem.gif','mppef.gif');
AVR(122, 'Phoenix','xm.gif','xf.gif');
AVR(12, 'Pixie','pim.gif','pif.gif');
AVR(159, 'Poison ivy','mppim.gif','mppif.gif');
AVR(348, 'Preystalker','mppym.gif','mppyf.gif');
AVR(360, 'Pterosaurus','ptm.gif','ptf.gif');
AVR(127, 'Pumpkin head','mjpmph.gif','mjpfph.gif');
AVR(109, 'Puppet','pu1.gif','pu2.gif');
AVR(82, 'Rabbit','rt1.gif','rt2.gif');
AVR(41, 'Rabid dog','mprd2.gif','mprd1.gif');
AVR(356, 'Raptor','rapm.gif','rapf.gif');
AVR(14, 'Rat','ra1.gif','ra2.gif');
AVR(287, 'Ratilian','mpratm.gif','mpratf.gif');
AVR(279, 'Ravenar','zom.gif','zof.gif');
AVR(346, 'Redcap','mprcm.gif','mprcf.gif');
AVR(337, 'Revenant','sc1.gif','sc2.gif');
AVR(365, 'Royal drake','mpdra9.gif','mpdra6.gif');
AVR(362, 'Sabretooth tiger','stm.gif','stf.gif');
AVR(149, 'Salamander','mpsam.gif','mpsaf.gif');
AVR(53, 'Sandworm','sw1.gif','sw2.gif');
AVR(102, 'Scarecrow','sa1.gif','sa2.gif');
AVR(115, 'Scavenger','mpscam.gif','mpscaf.gif');
AVR(146, 'Scorpion','mpscm.gif','mpscf.gif');
AVR(73, 'Sea deamon','se1.gif','se2.gif');
AVR(157, 'Sea dragon','mpsdm.gif','mpsdf.gif');
AVR(69, 'Sea horse','sem.gif','sef.gif');
AVR(67, 'Sea monster','so1.gif','so2.gif');
AVR(65, 'Sea snake','ssm.gif','ssf.gif');
AVR(51, 'Shade','mpsm.gif','mpsf.gif');
AVR(333, 'Shadow','ld1.gif','ld2.gif');
AVR(140, 'Shadow','mpsm.gif','mpsf.gif');
AVR(165, 'Shambling mounds','mpsmm.gif','mpsmf.gif');
AVR(155, 'Shark','mpshkm.gif','mpshkf.gif');
AVR(57, 'Sheep','shm.gif','shf.gif');
AVR(374, 'Ships cat','mpcatm.gif','mpcatf.gif');
AVR(378, 'Ships dog','mpcatm.gif','mpcatf.gif');
AVR(377, 'Ships monkey','mjmonk1.gif','mjmonk2.gif');
AVR(376, 'Ships parrot','mjpp1.gif','mjpp2.gif');
AVR(375, 'Ships rat','ra1.gif','ra2.gif');
AVR(320, 'Sidhee','mpsim.gif','mpsif.gif');
AVR(113, 'Sithanu','sim.gif','sif.gif');
AVR(27, 'Sithe lord','sd1.gif','sd2.gif');
AVR(26, 'Sithe scurge','ss1.gif','ss2.gif');
AVR(336, 'Skaven','sk1.gif','sk2.gif');
AVR(46, 'Skeleton','mpskem.gif','mpskef.gif');
AVR(48, 'Skeleton captain','sc1.gif','sc2.gif');
AVR(49, 'Skeleton mage','sm1.gif','sm2.gif');
AVR(47, 'Skeleton warrior','sk1.gif','sk2.gif');
AVR(135, 'Slammerkin','smm.gif','smf.gif');
AVR(372, 'Slayer demon','d1m.gif','d1f.gif');
AVR(355, 'Slug','sgm.gif','sgf.gif');
AVR(61, 'Snake','snm.gif','snf.gif');
AVR(92, 'Snow monster','sn1.gif','sn2.gif');
AVR(367, 'Souleater','mpsem.gif','mpsef.gif');
AVR(335, 'Specter','mpskem.gif','mpskef.gif');
AVR(62, 'Spider','sr1.gif','sr2.gif');
AVR(142, 'Spirit','mpspm.gif','mpspf.gif');
AVR(139, 'Spook','mpgham.gif','mpghaf.gif');
AVR(329, 'Spriggans','mpsrm.gif','mpsrf.gif');
AVR(278, 'Sprite','ws2.gif','ws1.gif');
AVR(359, 'Stegosaurus','stegm.gif','stegf.gif');
AVR(361, 'Stenopterygius','stem.gif','stef.gif');
AVR(163, 'Stinging nettle','mpsnm.gif','mpsnf.gif');
AVR(324, 'Sylphs','mpsym.gif','mpsyf.gif');
AVR(323, 'The bean sidhe','mpbsm.gif','mpbsf.gif');
AVR(322, 'The lhiannan-shee','mpism.gif','mpisf.gif');
AVR(151, 'Tiger','mptim.gif','mptif.gif');
AVR(118, 'Trenian','tem.gif','tef.gif');
AVR(357, 'Triceratops','trim.gif','trif.gif');
AVR(10, 'Troll','trm.gif','trf.gif');
AVR(321, 'Tuatha de danann','mptdm.gif','mptdf.gif');
AVR(70, 'Turtle','tt1.gif','tt2.gif');
AVR(84, 'Tuskamoth','tu1.gif','tu2.gif');
AVR(18, 'Undead','mpum.gif','mpuf.gif');
AVR(75, 'Undead pirate','mjpupm.gif','mjpupf.gif');
AVR(85, 'Unicorn','unm.gif','unf.gif');
AVR(24, 'Vampire','vam.gif','vaf.gif');
AVR(25, 'Vampire lord','vlm.gif','vlf.gif');
AVR(71, 'Water cow','wc1.gif','wc2.gif');
AVR(80, 'Water faerie','wfm.gif','wff.gif');
AVR(72, 'Water wisp','wwm.gif','wwf.gif');
AVR(81, 'Watuman','wam.gif','waf.gif');
AVR(32, 'Weaver','wef.gif','wem.gif');
AVR(111, 'Werewolf','wom.gif','wof.gif');
AVR(371, 'Whelp','mpwm.gif','mpwf.gif');
AVR(94, 'Wighte','wg1.gif','wg2.gif');
AVR(349, 'Winter elf','wim.gif','wif.gif');
AVR(345, 'Winter elf','ba1.gif','ba2.gif');
AVR(45, 'Wisp','ws2.gif','ws1.gif');
AVR(36, 'Witche','wi1.gif','wi2.gif');
AVR(37, 'Witche lord','wl1.gif','wl2.gif');
AVR(120, 'Wolf','wf2.gif','wf1.gif');
AVR(89, 'Woode','wd1.gif','wd2.gif');
AVR(342, 'Wraith','li1.gif','li2.gif');
AVR(280, 'Wretch','sk1.gif','sk2.gif');
AVR(276, 'Wyvern','ed1.gif','ed2.gif');
AVR(125, 'Yak','yk1.gif','yk2.gif');
AVR(74, 'Young weaver','ywm.gif','ywf.gif');
AVR(19, 'Zombie','mpzm.gif','mpzf.gif');
}
