export const CDN_RESOURCES_URL = new URL(import.meta.url).origin;
export const FHIP = `${CDN_RESOURCES_URL}/game/`;
export const FHIPI = `${FHIP}i/`;
export const FHIPM = `${FHIP}m/`;
export const FHIPR = `${FHIP}r/`;
export const FHIPB = `${FHIP}b/`;
export const FHIPO = `${FHIP}o/`;
export const FHIPH = `${FHIP}h/`;
export const FHIPS = `${FHIP}s/`;
export const FHIPV = `${FHIP}v/`;
export const FHIPIC = `${FHIP}icons/`;
export const FHIPIMG = `${CDN_RESOURCES_URL}/images/`