name: Deploy

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    timeout-minutes: 10
    container:
      image: ghcr.io/catthehacker/ubuntu:runner-latest
      volumes:
        - act-toolcache:/opt/hostedtoolcache
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: npm i
        run: npm i
        working-directory: .build
      - run: node .build/generate_chat_colors_css.mjs
      - run: npx -y stylelint --config .build/node_modules/stylelint-config-recommended/index.js css/chat/chat-colors.css
      - name: browserify analytics
        run: |
          npx --yes browserify -p common-shakeify analytics.js > $GITHUB_WORKSPACE/js/current/analytics.js
          npx --yes uglify-js --compress --mangle -- $GITHUB_WORKSPACE/js/current/analytics.js
        working-directory: .build
      - run: pip install s3cmd
        if: ${{ github.ref == 'refs/heads/master' }}
      - name: Publish
        run: s3cmd sync --no-mime-magic --guess-mime-type --access_key=${{ secrets.AWS_ACCESS_KEY_ID }} --secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} --host=${{ secrets.AWS_ENDPOINT_URL }} --host-bucket=${{ secrets.AWS_ENDPOINT_URL }} --bucket-location=auto --delete-removed --delete-after --no-preserve --recursive --rexclude "^\..*$" . 's3://lohimg'
        if: ${{ github.ref == 'refs/heads/master' }}
      - name: Purge cache
        run: 'curl -X POST https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_TOKEN }}" -H "Content-Type: application/json" --data "{\"purge_everything\":true}"'
        if: ${{ github.ref == 'refs/heads/master' }}
